// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { ChangeStruct } from "./change_struct_type";
// Mark import as potentially unused
declare type __keep_ChangeStruct = ChangeStruct;


export type AuditLog = {
  id: number,
  unixTime: bigint,
  identity: __Identity,
  nickname: string,
  reducer: string,
  oldChange: ChangeStruct,
  newChange: ChangeStruct,
};
/**
 * An object for generated helper functions.
 */
export const AuditLog = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    return __AlgebraicTypeValue.Product({
      elements: [
        { name: "id", algebraicType: __AlgebraicTypeValue.U32},
        { name: "unixTime", algebraicType: __AlgebraicTypeValue.I64},
        { name: "identity", algebraicType: __AlgebraicTypeValue.createIdentityType()},
        { name: "nickname", algebraicType: __AlgebraicTypeValue.String},
        { name: "reducer", algebraicType: __AlgebraicTypeValue.String},
        { name: "oldChange", algebraicType: ChangeStruct.getTypeScriptAlgebraicType()},
        { name: "newChange", algebraicType: ChangeStruct.getTypeScriptAlgebraicType()},
      ]
    });
  },

  serialize(writer: __BinaryWriter, value: AuditLog): void {
    __AlgebraicTypeValue.serializeValue(writer, AuditLog.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): AuditLog {
    return __AlgebraicTypeValue.deserializeValue(reader, AuditLog.getTypeScriptAlgebraicType());
  },

}

export default AuditLog;


