// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
} from "spacetimedb";
import { ElementDataChange as ElementDataChangeType } from "./element_data_change_type";
// Mark import as potentially unused
declare type __keep_ElementDataChangeType = ElementDataChangeType;
import { ElementChange as ElementChangeType } from "./element_change_type";
// Mark import as potentially unused
declare type __keep_ElementChangeType = ElementChangeType;
import { GuestChange as GuestChangeType } from "./guest_change_type";
// Mark import as potentially unused
declare type __keep_GuestChangeType = GuestChangeType;
import { EmptyChange as EmptyChangeType } from "./empty_change_type";
// Mark import as potentially unused
declare type __keep_EmptyChangeType = EmptyChangeType;
import { ChatMessage as ChatMessageType } from "./chat_message_type";
// Mark import as potentially unused
declare type __keep_ChatMessageType = ChatMessageType;


export type ElementDataChange = { tag: "ElementDataChange", value: ElementDataChangeType };
export type ElementChange = { tag: "ElementChange", value: ElementChangeType };
export type GuestChange = { tag: "GuestChange", value: GuestChangeType };
export type EmptyChange = { tag: "EmptyChange", value: EmptyChangeType };
export type ChatMessage = { tag: "ChatMessage", value: ChatMessageType };

