// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

export type Config = {
  version: number,
  ownerIdentity: __Identity,
  streamingPlatform: string,
  streamName: string,
  debugMode: boolean,
  updateHz: number,
  editorBorder: number,
  authentication: boolean,
  strictMode: boolean,
  editorGuidelines: string,
  configInit: boolean,
};
let _cached_Config_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const Config = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_Config_type_value) return _cached_Config_type_value;
    _cached_Config_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_Config_type_value.value.elements.push(
      { name: "version", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "ownerIdentity", algebraicType: __AlgebraicTypeValue.createIdentityType() },
      { name: "streamingPlatform", algebraicType: __AlgebraicTypeValue.String },
      { name: "streamName", algebraicType: __AlgebraicTypeValue.String },
      { name: "debugMode", algebraicType: __AlgebraicTypeValue.Bool },
      { name: "updateHz", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "editorBorder", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "authentication", algebraicType: __AlgebraicTypeValue.Bool },
      { name: "strictMode", algebraicType: __AlgebraicTypeValue.Bool },
      { name: "editorGuidelines", algebraicType: __AlgebraicTypeValue.String },
      { name: "configInit", algebraicType: __AlgebraicTypeValue.Bool },
    );
    return _cached_Config_type_value;
  },

  serialize(writer: __BinaryWriter, value: Config): void {
    __AlgebraicTypeValue.serializeValue(writer, Config.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): Config {
    return __AlgebraicTypeValue.deserializeValue(reader, Config.getTypeScriptAlgebraicType());
  },

}

export default Config;


