// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";
import { TextElement as TextElementType } from "./text_element_type";
// Mark import as potentially unused
declare type __keep_TextElementType = TextElementType;
import { ImageElement as ImageElementType } from "./image_element_type";
// Mark import as potentially unused
declare type __keep_ImageElementType = ImageElementType;
import { WidgetElement as WidgetElementType } from "./widget_element_type";
// Mark import as potentially unused
declare type __keep_WidgetElementType = WidgetElementType;


export type TextElement = { tag: "TextElement", value: TextElementType };
export type ImageElement = { tag: "ImageElement", value: ImageElementType };
export type WidgetElement = { tag: "WidgetElement", value: WidgetElementType };

