// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";
import { DataType as __DataType } from "./data_type_type";

export type ElementData = {
  id: number,
  name: string,
  dataType: __DataType,
  data: string,
  byteArray: Uint8Array | undefined,
  dataWidth: number,
  dataHeight: number,
  createdBy: string,
};

/**
 * A namespace for generated helper functions.
 */
export namespace ElementData {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createU32Type()),
      new ProductTypeElement("name", AlgebraicType.createStringType()),
      new ProductTypeElement("dataType", __DataType.getTypeScriptAlgebraicType()),
      new ProductTypeElement("data", AlgebraicType.createStringType()),
      new ProductTypeElement("byteArray", AlgebraicType.createOptionType(AlgebraicType.createArrayType(AlgebraicType.createU8Type()))),
      new ProductTypeElement("dataWidth", AlgebraicType.createI32Type()),
      new ProductTypeElement("dataHeight", AlgebraicType.createI32Type()),
      new ProductTypeElement("createdBy", AlgebraicType.createStringType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: ElementData): void {
    ElementData.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): ElementData {
    return ElementData.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


