// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

import {
  // @ts-ignore
  Address,
  // @ts-ignore
  AlgebraicType,
  // @ts-ignore
  AlgebraicValue,
  // @ts-ignore
  BinaryReader,
  // @ts-ignore
  BinaryWriter,
  // @ts-ignore
  CallReducerFlags,
  // @ts-ignore
  DBConnectionBuilder,
  // @ts-ignore
  DBConnectionImpl,
  // @ts-ignore
  DBContext,
  // @ts-ignore
  Event,
  // @ts-ignore
  EventContextInterface,
  // @ts-ignore
  Identity,
  // @ts-ignore
  ProductType,
  // @ts-ignore
  ProductTypeElement,
  // @ts-ignore
  SumType,
  // @ts-ignore
  SumTypeVariant,
  // @ts-ignore
  TableCache,
  // @ts-ignore
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
// @ts-ignore
import { ElementStruct as __ElementStruct } from "./element_struct_type";

export type Elements = {
  id: number,
  element: __ElementStruct,
  transparency: number,
  transform: string,
  clip: string,
  locked: boolean,
  folderId: number | undefined,
  layoutId: number,
  placedBy: string,
  lastEditedBy: string,
  zIndex: number,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Elements {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createU32Type()),
      new ProductTypeElement("element", __ElementStruct.getTypeScriptAlgebraicType()),
      new ProductTypeElement("transparency", AlgebraicType.createI32Type()),
      new ProductTypeElement("transform", AlgebraicType.createStringType()),
      new ProductTypeElement("clip", AlgebraicType.createStringType()),
      new ProductTypeElement("locked", AlgebraicType.createBoolType()),
      new ProductTypeElement("folderId", AlgebraicType.createOptionType(AlgebraicType.createU32Type())),
      new ProductTypeElement("layoutId", AlgebraicType.createU32Type()),
      new ProductTypeElement("placedBy", AlgebraicType.createStringType()),
      new ProductTypeElement("lastEditedBy", AlgebraicType.createStringType()),
      new ProductTypeElement("zIndex", AlgebraicType.createI32Type()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Elements): void {
    Elements.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Elements {
    return Elements.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


