// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import { __SPACETIMEDB__, AlgebraicType, ProductType, BuiltinType, ProductTypeElement, SumType, SumTypeVariant, DatabaseTable, AlgebraicValue, ReducerEvent, Identity, Address, ClientDB, SpacetimeDBClient } from "@clockworklabs/spacetimedb-sdk";

export class Folders extends DatabaseTable
{
	public static db: ClientDB = __SPACETIMEDB__.clientDB;
	public static tableName = "Folders";
	public id: number;
	public icon: string;
	public name: string;
	public createdBy: string;

	public static primaryKey: string | undefined = "id";

	constructor(id: number, icon: string, name: string, createdBy: string) {
	super();
		this.id = id;
		this.icon = icon;
		this.name = name;
		this.createdBy = createdBy;
	}

	public static serialize(value: Folders): object {
		return [
		value.id, value.icon, value.name, value.createdBy
		];
	}

	public static getAlgebraicType(): AlgebraicType
	{
		return AlgebraicType.createProductType([
			new ProductTypeElement("id", AlgebraicType.createPrimitiveType(BuiltinType.Type.U32)),
			new ProductTypeElement("icon", AlgebraicType.createPrimitiveType(BuiltinType.Type.String)),
			new ProductTypeElement("name", AlgebraicType.createPrimitiveType(BuiltinType.Type.String)),
			new ProductTypeElement("createdBy", AlgebraicType.createPrimitiveType(BuiltinType.Type.String)),
		]);
	}

	public static fromValue(value: AlgebraicValue): Folders
	{
		let productValue = value.asProductValue();
		let __Id = productValue.elements[0].asNumber();
		let __Icon = productValue.elements[1].asString();
		let __Name = productValue.elements[2].asString();
		let __CreatedBy = productValue.elements[3].asString();
		return new this(__Id, __Icon, __Name, __CreatedBy);
	}

	public static *filterById(value: number): IterableIterator<Folders>
	{
		for (let instance of this.db.getTable("Folders").getInstances())
		{
			if (instance.id === value) {
				yield instance;
			}
		}
	}

	public static findById(value: number): Folders | undefined
	{
		return this.filterById(value).next().value;
	}

	public static *filterByIcon(value: string): IterableIterator<Folders>
	{
		for (let instance of this.db.getTable("Folders").getInstances())
		{
			if (instance.icon === value) {
				yield instance;
			}
		}
	}

	public static *filterByName(value: string): IterableIterator<Folders>
	{
		for (let instance of this.db.getTable("Folders").getInstances())
		{
			if (instance.name === value) {
				yield instance;
			}
		}
	}

	public static *filterByCreatedBy(value: string): IterableIterator<Folders>
	{
		for (let instance of this.db.getTable("Folders").getInstances())
		{
			if (instance.createdBy === value) {
				yield instance;
			}
		}
	}


}

export default Folders;
