// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import { __SPACETIMEDB__, AlgebraicType, ProductType, BuiltinType, ProductTypeElement, SumType, SumTypeVariant, DatabaseTable, AlgebraicValue, ReducerEvent, Identity, Address, ClientDB, SpacetimeDBClient } from "@clockworklabs/spacetimedb-sdk";

export class GuestChange extends DatabaseTable
{
	public static db: ClientDB = __SPACETIMEDB__.clientDB;
	public static tableName = "GuestChange";
	public identity: Identity;
	public nickname: string;
	public color: string;
	public selectedElementId: number;
	public positionX: number;
	public positionY: number;

	public static primaryKey: string | undefined = undefined;

	constructor(identity: Identity, nickname: string, color: string, selectedElementId: number, positionX: number, positionY: number) {
	super();
		this.identity = identity;
		this.nickname = nickname;
		this.color = color;
		this.selectedElementId = selectedElementId;
		this.positionX = positionX;
		this.positionY = positionY;
	}

	public static serialize(value: GuestChange): object {
		return [
		Array.from(value.identity.toUint8Array()), value.nickname, value.color, value.selectedElementId, value.positionX, value.positionY
		];
	}

	public static getAlgebraicType(): AlgebraicType
	{
		return AlgebraicType.createProductType([
			new ProductTypeElement("identity", AlgebraicType.createProductType([
			new ProductTypeElement("__identity_bytes", AlgebraicType.createArrayType(AlgebraicType.createPrimitiveType(BuiltinType.Type.U8))),
		])),
			new ProductTypeElement("nickname", AlgebraicType.createPrimitiveType(BuiltinType.Type.String)),
			new ProductTypeElement("color", AlgebraicType.createPrimitiveType(BuiltinType.Type.String)),
			new ProductTypeElement("selectedElementId", AlgebraicType.createPrimitiveType(BuiltinType.Type.U32)),
			new ProductTypeElement("positionX", AlgebraicType.createPrimitiveType(BuiltinType.Type.I32)),
			new ProductTypeElement("positionY", AlgebraicType.createPrimitiveType(BuiltinType.Type.I32)),
		]);
	}

	public static fromValue(value: AlgebraicValue): GuestChange
	{
		let productValue = value.asProductValue();
		let __Identity = new Identity(productValue.elements[0].asProductValue().elements[0].asBytes());
		let __Nickname = productValue.elements[1].asString();
		let __Color = productValue.elements[2].asString();
		let __SelectedElementId = productValue.elements[3].asNumber();
		let __PositionX = productValue.elements[4].asNumber();
		let __PositionY = productValue.elements[5].asNumber();
		return new this(__Identity, __Nickname, __Color, __SelectedElementId, __PositionX, __PositionY);
	}

}

export default GuestChange;
