// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

import {
  // @ts-ignore
  Address,
  // @ts-ignore
  AlgebraicType,
  // @ts-ignore
  AlgebraicValue,
  // @ts-ignore
  BinaryReader,
  // @ts-ignore
  BinaryWriter,
  // @ts-ignore
  CallReducerFlags,
  // @ts-ignore
  DBConnectionBuilder,
  // @ts-ignore
  DBConnectionImpl,
  // @ts-ignore
  DBContext,
  // @ts-ignore
  Event,
  // @ts-ignore
  EventContextInterface,
  // @ts-ignore
  Identity,
  // @ts-ignore
  ProductType,
  // @ts-ignore
  ProductTypeElement,
  // @ts-ignore
  SumType,
  // @ts-ignore
  SumTypeVariant,
  // @ts-ignore
  TableCache,
  // @ts-ignore
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
export type Guests = {
  address: Address,
  identity: Identity,
  nickname: string,
  color: string,
  selectedElementId: number,
  selectedLayoutId: number,
  positionX: number,
  positionY: number,
  authenticated: boolean,
};

/**
 * A namespace for generated helper functions.
 */
export namespace Guests {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("address", AlgebraicType.createAddressType()),
      new ProductTypeElement("identity", AlgebraicType.createIdentityType()),
      new ProductTypeElement("nickname", AlgebraicType.createStringType()),
      new ProductTypeElement("color", AlgebraicType.createStringType()),
      new ProductTypeElement("selectedElementId", AlgebraicType.createU32Type()),
      new ProductTypeElement("selectedLayoutId", AlgebraicType.createU32Type()),
      new ProductTypeElement("positionX", AlgebraicType.createI32Type()),
      new ProductTypeElement("positionY", AlgebraicType.createI32Type()),
      new ProductTypeElement("authenticated", AlgebraicType.createBoolType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: Guests): void {
    Guests.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): Guests {
    return Guests.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


