// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

export type Guests = {
  address: __ConnectionId,
  identity: __Identity,
  nickname: string,
  color: string,
  selectedElementId: number,
  selectedLayoutId: number,
  positionX: number,
  positionY: number,
  authenticated: boolean,
};
let _cached_Guests_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const Guests = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_Guests_type_value) return _cached_Guests_type_value;
    _cached_Guests_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_Guests_type_value.value.elements.push(
      { name: "address", algebraicType: __AlgebraicTypeValue.createConnectionIdType() },
      { name: "identity", algebraicType: __AlgebraicTypeValue.createIdentityType() },
      { name: "nickname", algebraicType: __AlgebraicTypeValue.String },
      { name: "color", algebraicType: __AlgebraicTypeValue.String },
      { name: "selectedElementId", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "selectedLayoutId", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "positionX", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "positionY", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "authenticated", algebraicType: __AlgebraicTypeValue.Bool },
    );
    return _cached_Guests_type_value;
  },

  serialize(writer: __BinaryWriter, value: Guests): void {
    __AlgebraicTypeValue.serializeValue(writer, Guests.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): Guests {
    return __AlgebraicTypeValue.deserializeValue(reader, Guests.getTypeScriptAlgebraicType());
  },

}

export default Guests;


