// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit fb41e50eb73573b70eea532aeb6158eaac06fae0).

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  Identity,
  ProductType,
  ProductTypeElement,
  SubscriptionBuilderImpl,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
  type CallReducerFlags,
  type DbContext,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

import { ElementStruct as __ElementStruct } from "./element_struct_type";

export type ImportElement = {
  element: __ElementStruct,
  transparency: number,
  transform: string,
  clip: string,
  layoutId: number,
  placedBy: string,
  lastEditedBy: string,
  zindex: number,
  folderId: number | undefined,
};

/**
 * A namespace for generated helper functions.
 */
export namespace ImportElement {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("element", __ElementStruct.getTypeScriptAlgebraicType()),
      new ProductTypeElement("transparency", AlgebraicType.createI32Type()),
      new ProductTypeElement("transform", AlgebraicType.createStringType()),
      new ProductTypeElement("clip", AlgebraicType.createStringType()),
      new ProductTypeElement("layoutId", AlgebraicType.createU32Type()),
      new ProductTypeElement("placedBy", AlgebraicType.createStringType()),
      new ProductTypeElement("lastEditedBy", AlgebraicType.createStringType()),
      new ProductTypeElement("zindex", AlgebraicType.createI32Type()),
      new ProductTypeElement("folderId", AlgebraicType.createOptionType(AlgebraicType.createU32Type())),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: ImportElement): void {
    ImportElement.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): ImportElement {
    return ImportElement.getTypeScriptAlgebraicType().deserialize(reader);
  }

}

