// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

import { DataType } from "./data_type_type";
// Mark import as potentially unused
declare type __keep_DataType = DataType;

export type ImportElementData = {
  id: number,
  name: string,
  type: DataType,
  data: string,
  byteArray: Uint8Array,
  width: number,
  height: number,
  folderId: number,
  createdBy: string,
};
let _cached_ImportElementData_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const ImportElementData = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_ImportElementData_type_value) return _cached_ImportElementData_type_value;
    _cached_ImportElementData_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_ImportElementData_type_value.value.elements.push(
      { name: "id", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "name", algebraicType: __AlgebraicTypeValue.String },
      { name: "type", algebraicType: DataType.getTypeScriptAlgebraicType() },
      { name: "data", algebraicType: __AlgebraicTypeValue.String },
      { name: "byteArray", algebraicType: __AlgebraicTypeValue.Array(__AlgebraicTypeValue.U8) },
      { name: "width", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "height", algebraicType: __AlgebraicTypeValue.I32 },
      { name: "folderId", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "createdBy", algebraicType: __AlgebraicTypeValue.String },
    );
    return _cached_ImportElementData_type_value;
  },

  serialize(writer: __BinaryWriter, value: ImportElementData): void {
    __AlgebraicTypeValue.serializeValue(writer, ImportElementData.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): ImportElementData {
    return __AlgebraicTypeValue.deserializeValue(reader, ImportElementData.getTypeScriptAlgebraicType());
  },

}

export default ImportElementData;

