// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  AlgebraicType,
  AlgebraicValue,
  BinaryReader,
  BinaryWriter,
  CallReducerFlags,
  ConnectionId,
  DbConnectionBuilder,
  DbConnectionImpl,
  DbContext,
  ErrorContextInterface,
  Event,
  EventContextInterface,
  Identity,
  ProductType,
  ProductTypeElement,
  ReducerEventContextInterface,
  SubscriptionBuilderImpl,
  SubscriptionEventContextInterface,
  SumType,
  SumTypeVariant,
  TableCache,
  TimeDuration,
  Timestamp,
  deepEqual,
} from "@clockworklabs/spacetimedb-sdk";
import { CommandType as __CommandType } from "./command_type_type";

export type OverlayCommand = {
  id: number,
  command: __CommandType,
  issuedBy: Identity,
  timestamp: bigint,
  completed: boolean,
};

/**
 * A namespace for generated helper functions.
 */
export namespace OverlayCommand {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  export function getTypeScriptAlgebraicType(): AlgebraicType {
    return AlgebraicType.createProductType([
      new ProductTypeElement("id", AlgebraicType.createU32Type()),
      new ProductTypeElement("command", __CommandType.getTypeScriptAlgebraicType()),
      new ProductTypeElement("issuedBy", AlgebraicType.createIdentityType()),
      new ProductTypeElement("timestamp", AlgebraicType.createI64Type()),
      new ProductTypeElement("completed", AlgebraicType.createBoolType()),
    ]);
  }

  export function serialize(writer: BinaryWriter, value: OverlayCommand): void {
    OverlayCommand.getTypeScriptAlgebraicType().serialize(writer, value);
  }

  export function deserialize(reader: BinaryReader): OverlayCommand {
    return OverlayCommand.getTypeScriptAlgebraicType().deserialize(reader);
  }

}


