// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  AlgebraicType as __AlgebraicTypeValue,
  BinaryReader as __BinaryReader,
  BinaryWriter as __BinaryWriter,
  ClientCache as __ClientCache,
  ConnectionId as __ConnectionId,
  DbConnectionBuilder as __DbConnectionBuilder,
  DbConnectionImpl as __DbConnectionImpl,
  Identity as __Identity,
  SubscriptionBuilderImpl as __SubscriptionBuilderImpl,
  TableCache as __TableCache,
  TimeDuration as __TimeDuration,
  Timestamp as __Timestamp,
  deepEqual as __deepEqual,
  type AlgebraicType as __AlgebraicTypeType,
  type AlgebraicTypeVariants as __AlgebraicTypeVariants,
  type CallReducerFlags as __CallReducerFlags,
  type ErrorContextInterface as __ErrorContextInterface,
  type Event as __Event,
  type EventContextInterface as __EventContextInterface,
  type ReducerEventContextInterface as __ReducerEventContextInterface,
  type SubscriptionEventContextInterface as __SubscriptionEventContextInterface,
  type TableHandle as __TableHandle,
} from "spacetimedb";

export type SetConfig = {
  platform: string,
  channel: string,
  debug: boolean,
  updateHz: number,
  editorBorder: number,
  authentication: boolean,
  strictMode: boolean,
  authKey: string,
};
let _cached_SetConfig_type_value: __AlgebraicTypeType | null = null;

/**
 * An object for generated helper functions.
 */
export const SetConfig = {
  /**
  * A function which returns this type represented as an AlgebraicType.
  * This function is derived from the AlgebraicType used to generate this type.
  */
  getTypeScriptAlgebraicType(): __AlgebraicTypeType {
    if (_cached_SetConfig_type_value) return _cached_SetConfig_type_value;
    _cached_SetConfig_type_value = __AlgebraicTypeValue.Product({ elements: [] });
    _cached_SetConfig_type_value.value.elements.push(
      { name: "platform", algebraicType: __AlgebraicTypeValue.String },
      { name: "channel", algebraicType: __AlgebraicTypeValue.String },
      { name: "debug", algebraicType: __AlgebraicTypeValue.Bool },
      { name: "updateHz", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "editorBorder", algebraicType: __AlgebraicTypeValue.U32 },
      { name: "authentication", algebraicType: __AlgebraicTypeValue.Bool },
      { name: "strictMode", algebraicType: __AlgebraicTypeValue.Bool },
      { name: "authKey", algebraicType: __AlgebraicTypeValue.String },
    );
    return _cached_SetConfig_type_value;
  },

  serialize(writer: __BinaryWriter, value: SetConfig): void {
    __AlgebraicTypeValue.serializeValue(writer, SetConfig.getTypeScriptAlgebraicType(), value);
  },

  deserialize(reader: __BinaryReader): SetConfig {
    return __AlgebraicTypeValue.deserializeValue(reader, SetConfig.getTypeScriptAlgebraicType());
  },

}

export default SetConfig;

