// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import { __SPACETIMEDB__, AlgebraicType, ProductType, BuiltinType, ProductTypeElement, DatabaseTable, AlgebraicValue, ReducerArgsAdapter, SumTypeVariant, Serializer, Identity, Address, ReducerEvent, Reducer, SpacetimeDBClient } from "@clockworklabs/spacetimedb-sdk";

export class UpdateGuestSelectedLayoutByGuestIdReducer extends Reducer
{
	public static reducerName: string = "UpdateGuestSelectedLayoutByGuestId";
	public static call(_guestId: number, _selectedLayoutId: number) {
		this.getReducer().call(_guestId, _selectedLayoutId);
	}

	public call(_guestId: number, _selectedLayoutId: number) {
		const serializer = this.client.getSerializer();
		let _guestIdType = AlgebraicType.createPrimitiveType(BuiltinType.Type.U32);
		serializer.write(_guestIdType, _guestId);
		let _selectedLayoutIdType = AlgebraicType.createPrimitiveType(BuiltinType.Type.U32);
		serializer.write(_selectedLayoutIdType, _selectedLayoutId);
		this.client.call("UpdateGuestSelectedLayoutByGuestId", serializer);
	}

	public static deserializeArgs(adapter: ReducerArgsAdapter): any[] {
		let guestIdType = AlgebraicType.createPrimitiveType(BuiltinType.Type.U32);
		let guestIdValue = AlgebraicValue.deserialize(guestIdType, adapter.next())
		let guestId = guestIdValue.asNumber();
		let selectedLayoutIdType = AlgebraicType.createPrimitiveType(BuiltinType.Type.U32);
		let selectedLayoutIdValue = AlgebraicValue.deserialize(selectedLayoutIdType, adapter.next())
		let selectedLayoutId = selectedLayoutIdValue.asNumber();
		return [guestId, selectedLayoutId];
	}

	public static on(callback: (reducerEvent: ReducerEvent, _guestId: number, _selectedLayoutId: number) => void) {
		this.getReducer().on(callback);
	}
	public on(callback: (reducerEvent: ReducerEvent, _guestId: number, _selectedLayoutId: number) => void)
	{
		this.client.on("reducer:UpdateGuestSelectedLayoutByGuestId", callback);
	}
}


export default UpdateGuestSelectedLayoutByGuestIdReducer
