// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import { __SPACETIMEDB__, AlgebraicType, ProductType, BuiltinType, ProductTypeElement, DatabaseTable, AlgebraicValue, ReducerArgsAdapter, SumTypeVariant, Serializer, Identity, Address, ReducerEvent, Reducer, SpacetimeDBClient } from "@clockworklabs/spacetimedb-sdk";

export class UpdateElementZIndexReducer extends Reducer
{
	public static reducerName: string = "UpdateElementZIndex";
	public static call(_elementId: number, _zIndex: number) {
		this.getReducer().call(_elementId, _zIndex);
	}

	public call(_elementId: number, _zIndex: number) {
		const serializer = this.client.getSerializer();
		let _elementIdType = AlgebraicType.createPrimitiveType(BuiltinType.Type.U32);
		serializer.write(_elementIdType, _elementId);
		let _zIndexType = AlgebraicType.createPrimitiveType(BuiltinType.Type.I32);
		serializer.write(_zIndexType, _zIndex);
		this.client.call("UpdateElementZIndex", serializer);
	}

	public static deserializeArgs(adapter: ReducerArgsAdapter): any[] {
		let elementIdType = AlgebraicType.createPrimitiveType(BuiltinType.Type.U32);
		let elementIdValue = AlgebraicValue.deserialize(elementIdType, adapter.next())
		let elementId = elementIdValue.asNumber();
		let zIndexType = AlgebraicType.createPrimitiveType(BuiltinType.Type.I32);
		let zIndexValue = AlgebraicValue.deserialize(zIndexType, adapter.next())
		let zIndex = zIndexValue.asNumber();
		return [elementId, zIndex];
	}

	public static on(callback: (reducerEvent: ReducerEvent, _elementId: number, _zIndex: number) => void) {
		this.getReducer().on(callback);
	}
	public on(callback: (reducerEvent: ReducerEvent, _elementId: number, _zIndex: number) => void)
	{
		this.client.on("reducer:UpdateElementZIndex", callback);
	}
}


export default UpdateElementZIndexReducer
