// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

// @ts-ignore
import { __SPACETIMEDB__, AlgebraicType, ProductType, BuiltinType, ProductTypeElement, SumType, SumTypeVariant, DatabaseTable, AlgebraicValue, ReducerEvent, Identity, Address, ClientDB, SpacetimeDBClient } from "@clockworklabs/spacetimedb-sdk";

export class ZIndex extends DatabaseTable
{
	public static db: ClientDB = __SPACETIMEDB__.clientDB;
	public static tableName = "ZIndex";
	public version: number;
	public min: number;
	public max: number;
	public ceiling: number;

	public static primaryKey: string | undefined = "version";

	constructor(version: number, min: number, max: number, ceiling: number) {
	super();
		this.version = version;
		this.min = min;
		this.max = max;
		this.ceiling = ceiling;
	}

	public static serialize(value: ZIndex): object {
		return [
		value.version, value.min, value.max, value.ceiling
		];
	}

	public static getAlgebraicType(): AlgebraicType
	{
		return AlgebraicType.createProductType([
			new ProductTypeElement("version", AlgebraicType.createPrimitiveType(BuiltinType.Type.U32)),
			new ProductTypeElement("min", AlgebraicType.createPrimitiveType(BuiltinType.Type.I32)),
			new ProductTypeElement("max", AlgebraicType.createPrimitiveType(BuiltinType.Type.I32)),
			new ProductTypeElement("ceiling", AlgebraicType.createPrimitiveType(BuiltinType.Type.I32)),
		]);
	}

	public static fromValue(value: AlgebraicValue): ZIndex
	{
		let productValue = value.asProductValue();
		let __Version = productValue.elements[0].asNumber();
		let __Min = productValue.elements[1].asNumber();
		let __Max = productValue.elements[2].asNumber();
		let __Ceiling = productValue.elements[3].asNumber();
		return new this(__Version, __Min, __Max, __Ceiling);
	}

	public static *filterByVersion(value: number): IterableIterator<ZIndex>
	{
		for (let instance of this.db.getTable("ZIndex").getInstances())
		{
			if (instance.version === value) {
				yield instance;
			}
		}
	}

	public static findByVersion(value: number): ZIndex | undefined
	{
		return this.filterByVersion(value).next().value;
	}

	public static *filterByMin(value: number): IterableIterator<ZIndex>
	{
		for (let instance of this.db.getTable("ZIndex").getInstances())
		{
			if (instance.min === value) {
				yield instance;
			}
		}
	}

	public static *filterByMax(value: number): IterableIterator<ZIndex>
	{
		for (let instance of this.db.getTable("ZIndex").getInstances())
		{
			if (instance.max === value) {
				yield instance;
			}
		}
	}

	public static *filterByCeiling(value: number): IterableIterator<ZIndex>
	{
		for (let instance of this.db.getTable("ZIndex").getInstances())
		{
			if (instance.ceiling === value) {
				yield instance;
			}
		}
	}


}

export default ZIndex;
