export enum PermissionTypes {
  None = 0,
  Whitelisted = 1,
  SendMessage = 2, 
  UpdateConfig = 3,
  UpdateAuthenticationKey = 4,
  UpdateEditorGuidelines = 5,
  AddElementData = 6,
  UpdateElementData = 7,
  DeleteElementData = 8,
  AddElement = 9,
  UpdateElement = 10,
  DeleteElement = 11,
  AddFolder = 12,
  UpdateFolder = 13,
  DeleteFolder = 14,
  KickGuest = 15,
  AddLayout = 16,
  UpdateLayout = 17,
  SetLayoutActive = 18,
  DeleteLayout = 19,
  IssueOverlayCommand = 20,
  ModifyPermissions = 21,
  ModifyWhitelist = 22,
  Editor = 9997,
  Moderator = 9998,
  Owner = 9999,
}