name: Build

on:
  push:
    branches-ignore:
      - refs/tags/v*
  release:
    types:
      - created

jobs:
  backend:
    name: SpacetimeDB Module
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"
          global-json-file: global.json

      - name: Verify dotnet version
        run: dotnet --info

      - name: Setup build env
        run: |
          sudo apt-get update && sudo apt-get install -y binaryen
          dotnet workload install wasi-experimental

      - name: Install SpacetimeDB CLI
        shell: bash
        run: |
          curl -sSf https://install.spacetimedb.com | sh -s -- -y
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build module
        run: |
          spacetime build -p server
          mv server/obj/Release/net8.0/wasi-wasm/wasm/for-publish/StdbModule.wasm pogly.wasm

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: spacetimedb-module
          path: pogly.wasm
          overwrite: true

  frontend:
    name: "Web"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Setup node.js"
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"
      - name: "Build web"
        run: |
          npm install
          npm run build
      # Disables warnings failing production builds
      #        env:
      #          CI: ""
      - name: "Upload artifact"
        uses: actions/upload-artifact@v4
        with:
          name: web-files
          path: build/
          overwrite: true

  #  deploy:
  #    name: "Deploy"
  #    needs: frontend
  #    if: >
  #      github.ref == 'refs/heads/main' ||
  #      github.ref == 'refs/heads/dev' ||
  #      startsWith(github.ref, 'refs/tags/v')
  #    uses: ./.github/workflows/deploy.yml
  #    secrets: inherit

  release:
    name: "Release"
    needs: [backend, frontend]
    if: github.event_name == 'release'
    uses: ./.github/workflows/release.yml
    secrets: inherit
