name: Deploy

on:
  workflow_call:

jobs:
  deploy_web:
    name: "${{ matrix.target }}"
    runs-on: self-hosted
    strategy:
      matrix:
        target: [ dev, prod ]
        isProd:
          - ${{ contains(github.ref, 'main') || startsWith(github.ref, 'refs/tags/v') }}
        exclude:
          - isProd: false
            target: prod
    if: github.event_name != 'pull_request'
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: web-files
      - uses: easingthemes/ssh-deploy@v5.1.0
        with:
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SSH_PRIVATE_KEY: ${{ secrets.REMOTE_SSH_KEY }}
          SOURCE: "."
          TARGET: "${{ secrets.REMOTE_DIR }}/${{ matrix.target }}"
          ARGS: "-avzr --delete"
